repos:
  - repo: local
    hooks:
      - id: hatch-fmt
        name: Hatch Formatter
        entry: hatch fmt --check
        language: system
        pass_filenames: false
      - id: hatch-test
        name: Hatch Tests
        entry: hatch test
        language: system
        pass_filenames: false
