site_name: Engramic Reference
theme:
  font:
    text: Raleway
  name: material
  logo: assets/logo_100.png
  favicon: assets/logo_100.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Host & Services: host_and_services.md
  - Profiles: profiles.md
  - How To's:
    - PDF Parse: howto/how_to_parse_documents.md
  - API Reference:
    - Engram: reference/emgram.md
    - Retrieve Service: 
      - Retrieve Service: reference/retrieve_service.md
      - Ask: reference/ask.md
    - Response Service: reference/response_service.md
    - Codify Service: reference/codify_service.md
    - Consolidate Service: reference/consolidate_service.md
    - Document Service:
      - Sense Service: reference/sense_service.md
      - Scan Service: reference/scan.md
    - Storage Service: reference/storage_service.md
    - Message Service: reference/message_service.md
    - Progress Service: reference/progress_service.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
  - search
  - mike:
      version_selector: true
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

extra:
  version:
    provider: mike
    default: 0.0