site_name: Engramic Reference
theme:
  font:
    text: Raleway
  name: material
  logo: assets/logo_100.png
  favicon: assets/logo_100.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Host & Services: host_and_services.md
  - Profiles: profiles.md
  - How To's: how_to.md
  - API Reference:
      - Engram: reference/emgram.md
      - Retrieve Service: 
        - Retrieve Service: reference/retrieve_service.md
        - Ask: reference/ask.md
      - Response Service: reference/response_service.md
      - Codify Service: reference/codify_service.md
      - Consolidate Service: reference/consolidate_service.md
      - Storage Service: reference/storage_service.md
      - Message Service: reference/message_service.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
  - search
  - mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  version:
    provider: mike