name: Deploy Documentation

on:
  push:
    branches:
      - main
      - feature/docs_and_tests
  workflow_dispatch:



jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Hatch
        run: pip install --user hatch

      - name: Add Hatch to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create docs environment
        run: hatch env create docs

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy versioned docs with mike
        run: |
          hatch run docs:deploy-docs
          hatch run docs:set-default-docs

      - name: Commit and push to gh-pages
        working-directory: site
        run: |
          git add .
          git commit -m "Deploy docs for version $(hatch version | cut -d. -f1,2)" || echo "No changes to commit"
          git push origin gh-pages
  