name: Deploy Documentation

on:
  push:
    branches:
      - main
      - feature/docs_and_tests
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Hatch
        run: pip install --user hatch

      - name: Add Hatch to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create docs environment
        run: hatch env create docs

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || echo "No gh-pages branch yet"

      - name: Deploy versioned docs with mike
        run: |
          
          if [ -n "${{ secrets.GH_PAGES_DEPLOY_TOKEN }}" ]; then
            echo "Using GH_PAGES_DEPLOY_TOKEN for authentication..."
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAGES_DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git
          else
            echo "::warning::No deploy token provided. Push may fail on protected branches or forks."
          fi

          hatch run docs:deploy-docs
          hatch run docs:set-default-docs
  